# Generated by Django 2.2.8 on 2021-01-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
    ]
